import { EstateData, HeirsData } from './inheritance-calculator';

export interface QuickExample {
  id: string;
  name: string;
  description: string;
  estate: EstateData;
  heirs: HeirsData;
}

export const QUICK_EXAMPLES: QuickExample[] = [
  {
    id: 'example-1',
    name: 'زوج وأم وأخت شقيقة',
    description: 'حالة بسيطة: الزوج يأخذ النصف، الأم الثلث، والأخت الشقيقة النصف (مع الرد)',
    estate: {
      total: 120000,
      funeral: 0,
      debts: 0,
      will: 0,
    },
    heirs: {
      husband: 1,
      wife: 0,
      father: 0,
      mother: 1,
      grandfather: 0,
      grandmother: 0,
      son: 0,
      daughter: 0,
      grandson: 0,
      granddaughter: 0,
      full_brother: 0,
      full_sister: 1,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 0,
      maternal_sister: 0,
    },
  },
  {
    id: 'example-2',
    name: 'أب وأم وابن وبنت',
    description: 'حالة معقدة: الأب والأم يأخذان الفروض، والابن والبنت يأخذان الباقي بالتعصيب',
    estate: {
      total: 240000,
      funeral: 0,
      debts: 0,
      will: 0,
    },
    heirs: {
      husband: 0,
      wife: 0,
      father: 1,
      mother: 1,
      grandfather: 0,
      grandmother: 0,
      son: 1,
      daughter: 1,
      grandson: 0,
      granddaughter: 0,
      full_brother: 0,
      full_sister: 0,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 0,
      maternal_sister: 0,
    },
  },
  {
    id: 'example-3',
    name: 'زوجة وأب وأم وإخوة',
    description: 'حالة العول: الفروض تزيد عن الأصل (الزوجة الربع، الأب السدس، الأم السدس)',
    estate: {
      total: 180000,
      funeral: 0,
      debts: 0,
      will: 0,
    },
    heirs: {
      husband: 0,
      wife: 1,
      father: 1,
      mother: 1,
      grandfather: 0,
      grandmother: 0,
      son: 0,
      daughter: 0,
      grandson: 0,
      granddaughter: 0,
      full_brother: 2,
      full_sister: 0,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 0,
      maternal_sister: 0,
    },
  },
  {
    id: 'example-4',
    name: 'ابن وبنتان وأخوات',
    description: 'حالة الرد: لا يوجد أصحاب فروض، فقط عاصب وذوو أرحام',
    estate: {
      total: 300000,
      funeral: 5000,
      debts: 10000,
      will: 0,
    },
    heirs: {
      husband: 0,
      wife: 0,
      father: 0,
      mother: 0,
      grandfather: 0,
      grandmother: 0,
      son: 1,
      daughter: 2,
      grandson: 0,
      granddaughter: 0,
      full_brother: 0,
      full_sister: 2,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 0,
      maternal_sister: 0,
    },
  },
  {
    id: 'example-5',
    name: 'أم وإخوة لأم وإخوة أشقاء',
    description: 'حالة الإخوة لأم: يرثون مع الأم والإخوة الأشقاء',
    estate: {
      total: 100000,
      funeral: 0,
      debts: 0,
      will: 0,
    },
    heirs: {
      husband: 0,
      wife: 0,
      father: 0,
      mother: 1,
      grandfather: 0,
      grandmother: 0,
      son: 0,
      daughter: 0,
      grandson: 0,
      granddaughter: 0,
      full_brother: 2,
      full_sister: 0,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 2,
      maternal_sister: 1,
    },
  },
  {
    id: 'example-6',
    name: 'زوجتان وأب وأم',
    description: 'حالة متعددة الزوجات: كل زوجة تأخذ نصيبها من الربع',
    estate: {
      total: 160000,
      funeral: 0,
      debts: 0,
      will: 0,
    },
    heirs: {
      husband: 0,
      wife: 2,
      father: 1,
      mother: 1,
      grandfather: 0,
      grandmother: 0,
      son: 0,
      daughter: 0,
      grandson: 0,
      granddaughter: 0,
      full_brother: 0,
      full_sister: 0,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 0,
      maternal_sister: 0,
    },
  },
  {
    id: 'example-7',
    name: 'بنات فقط (الرد)',
    description: 'حالة البنات فقط: يأخذن الثلثين بالفرض والباقي بالرد',
    estate: {
      total: 90000,
      funeral: 0,
      debts: 0,
      will: 0,
    },
    heirs: {
      husband: 0,
      wife: 0,
      father: 0,
      mother: 0,
      grandfather: 0,
      grandmother: 0,
      son: 0,
      daughter: 3,
      grandson: 0,
      granddaughter: 0,
      full_brother: 0,
      full_sister: 0,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 0,
      maternal_sister: 0,
    },
  },
  {
    id: 'example-8',
    name: 'جد وإخوة (حجب الجد)',
    description: 'حالة حجب الجد للإخوة: الجد يحجب الإخوة في بعض المذاهب',
    estate: {
      total: 200000,
      funeral: 0,
      debts: 0,
      will: 0,
    },
    heirs: {
      husband: 0,
      wife: 0,
      father: 0,
      mother: 1,
      grandfather: 1,
      grandmother: 0,
      son: 0,
      daughter: 0,
      grandson: 0,
      granddaughter: 0,
      full_brother: 2,
      full_sister: 1,
      paternal_brother: 0,
      paternal_sister: 0,
      maternal_brother: 0,
      maternal_sister: 0,
    },
  },
];

export function getExampleById(id: string): QuickExample | undefined {
  return QUICK_EXAMPLES.find(example => example.id === id);
}

export function getAllExamples(): QuickExample[] {
  return QUICK_EXAMPLES;
}
